disp(['L_tot = ',num2str(Ly),' x ',num2str(Lx),', ',...
    'h = ',num2str(h),', ',...
    'Kx = ',num2str(Kx),', ',...
    'Ky = ',num2str(Ky),', ',...
    'lambda = ',num2str(lambda),', ',...
    'PML thickness = ',num2str(BC{1}{2}(1)),', '...
    'PML beta = ',num2str(BC{1}{2}(2))])

disp(['L_mat = ',num2str(Ly_mat),' x ',num2str(Lx_mat),', ',...
    'chi = ',num2str(chi),', ',...
    'obj = ',obj_txt])

disp(' ')